# Generated by Django 4.2.7 on 2023-11-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rewiew',
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='review_related', to='post.review'),
        ),
    ]
